#!/bin/bash

g-update && g_updated=1
if [ ! -z "$g_updated" ]; then $0 $@; exit; fi # Update && re-execute

git add -u
git commit -m "Final working state"
git reset `git rev-parse master`
git checkout master
