#!/bin/bash
g-update && g_updated=1
if [ ! -z "$g_updated" ]; then $0 $@; exit; fi # Update && re-execute

working=working-${USER}-`hostname`
git checkout master || ! g-error $0 line $LINENO || exit 1 
git pull --no-edit origin master || ! g-error $0 line $LINENO || exit 1 
git push origin master || ! g-error $0 line $LINENO || exit 1 
git checkout $working || ! g-error $0 line $LINENO || exit 1 
git reset --hard ${working}@{1} || ! g-error $0 line $LINENO || exit 1 
git merge --no-edit master || ! g-error $0 line $LINENO || exit 1 
git push origin $working || ! g-error $0 line $LINENO || exit 1 
