#!/bin/bash

g-update && g_updated=1
if [ ! -z "$g_updated" ]; then $0 $@; exit; fi # Update && re-execute


date=`date +%Y-%m-%d`
timestr=$(($(date +'%s * 1000 + %-N / 1000000')))

if [ -z "$dir" ]; then
	if [ -z "$name" ]; then
		name=$timestr
	else
		name="${name}_${timestr}"
	fi
	dir=experiments/$name
fi
init_dir=$(pwd)

git checkout --quiet -B working || ! g-error $0 line $LINENO || exit 1
git pull --no-edit --quiet origin working || ! g-error $0 line $LINENO || exit 1
git add -u || ! g-error $0 line $LINENO || exit 1
git commit --quiet --allow-empty -m "Experiment $name" || ! g-error $0 line $LINENO || exit 1
git push --quiet origin working || ! g-error $0 line $LINENO || exit 1

current_origin=`git config remote.origin.url`
echo "Cloning $current_origin into in $dir"
mkdir -p "$dir"
cd "$dir"
git clone --quiet -b working --recurse-submodules --depth 1 $current_origin . || ! g-error $0 line $LINENO || exit 1
git remote set-url --push origin no_push || ! g-error $0 line $LINENO || exit 1

[ -f ./.g-run ] && ./.g-run
$@
