#!/bin/bash

cd `dirname "$0"`
git fetch
newcommits=`git rev-list HEAD..origin/master --count`
if [ "$newcommits" -gt "0" ]; then
	echo
	echo "g-working update available:"
	git log --pretty=oneline HEAD..origin/master | cat
	read -p "Install? (y/n) " yn
    case $yn in
        [Yy]* ) git pull origin master; exit 0 
    esac
fi
exit 1
