#!/bin/bash

g-update && g_updated=1
if [ ! -z "$g_updated" ]; then $0 $@; exit; fi # Update && re-execute

working=working-${USER}-`hostname`

git checkout -B $working || ! g-error $0 line $LINENO || exit 1
echo /experiments >> .gitignore
git add -u
git commit --allow-empty -m "work in progress" || ! g-error $0 line $LINENO || exit 1
git push origin $working || ! g-error $0 line $LINENO || exit 1 

exit 0
